@startuml
ExecutorState -> Device: Compute
Device -> OpKernel: Compute
OpKernel -> TrackingAllocator: Create
Device -> TrackingAllocator: AllocateRaw
TrackingAllocator -> TrackingAllocator: AddAllocateRecord
Device -> TrackingAllocator: DeallocateRaw
TrackingAllocator -> TrackingAllocator: AddAllocateRecord
ExecutorState -> NodeExecStats: SetMemory
NodeExecStats -> OpKernel: ConsumeWrappedAllocators
@enduml