@startuml

interface CntfProfilerInterface
interface CntfProfilerInterfaceSlim
interface CntfProfilerInterfaceEstimator
interface CntfProfilerInterfaceKeras

CntfProfilerInterface <|-- CntfProfilerInterfaceSlim
CntfProfilerInterface <|-- CntfProfilerInterfaceEstimator
CntfProfilerInterface <|-- CntfProfilerInterfaceKeras

class CntfProfiler
CntfProfilerInterfaceSlim <|-- CntfProfiler
CntfProfilerInterfaceEstimator <|-- CntfProfiler
CntfProfilerInterfaceKeras <|-- CntfProfiler


package Sampler {
    class CnSampler
    class CnMLUSampler
    class CnLinuxNetworkSampler
    class CnLinuxCPUSampler
    class CnLinuxMemorySampler
    CnSampler *-- CnMLUSampler
    CnSampler *-- CnLinuxCPUSampler
    CnSampler *-- CnLinuxNetworkSampler
    CnSampler *-- CnLinuxMemorySampler
}

package "Environment Collector"{
    class CnEnvCollector
    class OSEnvCollector
    class DeviceEnvCollector
    class RuntimeEnvCollector
    CnEnvCollector *-- OSEnvCollector
    CnEnvCollector *-- DeviceEnvCollector
    CnEnvCollector *-- RuntimeEnvCollector
}

package "Stats Generator"{
    class CntfStatsGenerator
    class Timeline 
    class TimelineGenerator
    Timeline <|-- TimelineGenerator
    class JsonGenerator
    class TensorboardGenerator
    CntfStatsGenerator *-- TimelineGenerator
    CntfStatsGenerator *-- JsonGenerator
    CntfStatsGenerator *-- TensorboardGenerator
}

CntfProfiler *-- CnSampler
CntfProfiler *-- CnEnvCollector
CntfProfiler *-- CntfStatsGenerator
@enduml