@startuml
start
:Create Profiler;
if (level = 0) 
    :Disable Activity Profiler;
    :Disable Harward Sampler;
    :Disable TF Profilers;
elseif (level = 1)
    :Enable Activity Profiler;
    :Disable Harward Sampler;
    :Disable TF Profilers;
elseif (level >= 2)
    :Enable Activity Profiler;
    :Enable Harward Sampler;
    :Enable TF Profilers;
endif

if (Activity Profiler on) then (yes)
:Trace Preprocess Activity;
else (no)
endif

fork
if (api = raw) 
repeat:Start Step;
    :Start Trace;
    :Session Run;
    :End Trace;
repeat while (has next step);
elseif (api = keras)
:Add Callback;
:Compile;
:Fit;
endif
:Profile PostProcess Activity;
fork again
if (sampler on) then (yes)
    :Star Hardware Sampler;
else (no)
endif
end fork

if (sampler on)
    :Stop Hardware Sampler;
endif

if (Activity Profiler on) then (yes)
:Trace Postprocess Activity;
else (no)
endif

:Collect Environment Infomation;
:Gernerate Profiler Data;
stop
@enduml